name: build
on:
- push
- pull_request
env:
   MAVEN_OPTS: -Xmx1g
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
            java-version: 1.8
      -  name: Cache Maven packages
         uses: actions/cache@v2
         with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
      -  name: Checkout exemple service
         uses: actions/checkout@v2
         with:
            path: exemple-service
            repository: doudouchat/exemple-service
      -  name: Build exemple service
         run: mvn -f ${{ github.workspace }}/exemple-service clean install -Dmaven.test.skip=true
      -  name: Checkout exemple authorization
         uses: actions/checkout@v2
         with:
            path: exemple-authorization
            repository: doudouchat/exemple-authorization
      -  name: Build exemple authorization
         run: mvn -f ${{ github.workspace }}/exemple-authorization clean install -Dmaven.test.skip=true
      -  name: Checkout exemple gateway
         uses: actions/checkout@v2
         with:
            path: exemple-gateway
            repository: doudouchat/exemple-gateway
            ref: 1.0.0
      -  name: Build exemple gateway
         run: mvn -f ${{ github.workspace }}/exemple-gateway clean install -Dmaven.test.skip=true
      -  name: Build exemple-embedded
         run: mvn clean verify